language: java
install: true

stages:
- name: build
- name: snapshot
  if: branch = development AND type = push
- name: release
  if: branch = master AND type = push

jobs:
  include:
  - stage: build
    script: ./gradlew build
  - stage: snapshot
    script: ./gradlew artifactoryPublish --exclude-task test -Dbintray.user=${BINTRAY_USER} -Dbintray.key=${BINTRAY_KEY} -Dbuild.number=${TRAVIS_BUILD_NUMBER}
  - stage: release
    script: ./gradlew bintrayUpload --exclude-task test -Drelease=true -PbuildVariant=release -Dbintray.user=${BINTRAY_USER} -Dbintray.key=${BINTRAY_KEY} -Dbuild.number=${TRAVIS_BUILD_NUMBER}

before_deploy: ./gradlew distZip --exclude-task test -PbuildVariant=release

deploy:
  provider: releases
  api_key: ${ACCESS_TOKEN}
  skip_cleanup: true
  file: build/dist/dxram.zip
  on:
    repo: hhu-bsinfo/dxram
    branch: master
    tags: true
